POST http://localhost:3005/login HTTP/1.1

###
POST http://localhost:3005/login HTTP/1.1
Content-Type: application/json

{
  "email":"john@mail.com",
  "password":"john123"
}

###
POST http://localhost:3005/test HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjIzMDUyNDA2LCJleHAiOjE2MjMyMjUyMDZ9.EmD4JhziHt2jYgGvLZQN0cgNsc5-w78RGftRMughmYA

{
  "data":"lot of data"
}